language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t wil778/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wil778/docker-react npm run test

#   script:
#     - docker run USERNAME/docker-react npm run test -- --coverage
