language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t wil778/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wil778/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-us-east-2-595834449315
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
#   script:
#     - docker run USERNAME/docker-react npm run test -- --coverage

